# Defines the User Interface (UI) for the Shiny application.
library(shiny)

# Define the UI using a fluidPage layout
# fluidPage provides a responsive layout that adjusts to the browser window size.
ui <- fluidPage(

  tags$head(
    includeCSS("www/styles.css"),
    tags$link(
      rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    ),
    tags$title("PRS Explorer")
  ),


  div(
    id = 'main-container',

    # --- SideBar Menu ---
    div(
      id = 'main-sidebar',
      div(
        id = 'logo',
        div(
          id = 'logo-icon',
          tags$span(class="material-symbols-outlined", "explore")
        ),
        div(
          id = 'logo-text',
          tags$p(id = 'logo-maintext', "Poligenic Risk Score"),
          tags$p(id = 'logo-subtext', "Explorer")
        )
      )
      
    ),

    # --- Plot Area  ---
    div(
      id = 'main-content',
      div(
        id = 'plot-distribuition',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-metrics',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-orperquantile',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-prevalenceperquantile',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-roc',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-topOR',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-ttest',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-AUROC',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-r2',
        class = 'plot-panel'
      ),
      div(
        id = 'plot-beta',
        class = 'plot-panel'
      )
    )
  )
  # # Application title displayed at the top
  # titlePanel("Basic Shiny App Example"),

  # # Sidebar layout: common structure with a sidebar for inputs and a main area for outputs
  # sidebarLayout(

  #   # Sidebar panel: Contains input controls
  #   sidebarPanel(
  #     width = 4, # Adjust sidebar width (optional, default is 4 out of 12 columns)

  #     # Input control: Slider
  #     # Allows the user to select a number within a defined range.
  #     sliderInput(inputId = "bins",                # Unique ID to access this input's value in the server
  #                 label = "Number of bins:",       # Text label displayed above the slider
  #                 min = 5,                         # Minimum selectable value
  #                 max = 50,                        # Maximum selectable value
  #                 value = 30,                      # Default value when the app starts
  #                 step = 1),                       # Increment step of the slider

  #     # Input control: Radio buttons
  #     # Allows the user to choose one option from a set.
  #     radioButtons(inputId = "color",
  #                  label = "Select histogram color:",
  #                  choices = c("Sky Blue" = "skyblue",
  #                              "Light Green" = "lightgreen",
  #                              "Grey" = "grey"),
  #                  selected = "skyblue") # Default selected option
  #   ),

  #   # Main panel: Displays the outputs generated by the server
  #   mainPanel(
  #     width = 8, # Adjust main panel width (optional, default is 8 out of 12 columns)

  #     # Output element: Plot
  #     # Reserves space to display a plot generated by the server.
  #     # The outputId 'distPlot' must match an output object created in the server function.
  #     plotOutput(outputId = "distPlot"),

  #     # Output element: Text
  #     # Reserves space to display text generated by the server.
  #     h4("Summary Statistics"), # Static heading
  #     verbatimTextOutput(outputId = "summary") # Displays fixed-width text output

  #   ) # End of mainPanel
  # ) # End of sidebarLayout
) # End of fluidPage
